# Generated by Django 4.2.11 on 2025-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='logo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
