# Generated by Django 4.2.11 on 2025-08-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_purchase_remove_supplier_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='invoice_number',
            new_name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.purchase')),
            ],
        ),
    ]
