# Generated by Django 4.2.11 on 2025-08-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_rename_invoice_number_purchase_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
