# Generated by Django 4.2.11 on 2025-08-17 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('percent_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_paid_by_customer', models.BooleanField(default=True)),
                ('enable_credit', models.BooleanField(default=True)),
                ('enable_transfer', models.BooleanField(default=True)),
                ('enable_qris', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('proof', models.FileField(blank=True, null=True, upload_to='payments/proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.bank')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payments', to='pos.transaction')),
            ],
        ),
    ]
