# Generated by Django 4.2.11 on 2025-08-17 15:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_bank_bankpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsEarningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('min_total', models.DecimalField(decimal_places=2, help_text='Minimal total belanja', max_digits=12)),
                ('points_awarded', models.PositiveIntegerField(help_text='Poin yang didapat bila total >= min_total')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_total'],
            },
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(help_text='+ untuk earn, - untuk redeem')),
                ('balance_after', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointsRedemptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('points_required', models.PositiveIntegerField(help_text='Poin yang dibutuhkan')),
                ('detail', models.CharField(blank=True, default='', help_text='Detalle (mis. Diskon $5)', max_length=255)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Nominal diskon uang saat ditebus (opsional, bisa 0)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['points_required'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('rejected', 'rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('credit', 'Credit'), ('qris', 'QRIS')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='uniq_product_warehouse'),
        ),
        migrations.AddField(
            model_name='pointsledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger', to='pos.customer'),
        ),
        migrations.AddField(
            model_name='pointsledger',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='pos.transaction'),
        ),
    ]
