"""
Django settings for posbackend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent.parent

from pos.utils.path import get_user_data_path
USER_DATA_PATH = get_user_data_path()
os.makedirs(USER_DATA_PATH, exist_ok=True)


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'backend', 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-m0=0#%y=k853=nu+%$#_e6me_r%b0!tkr6m&q1z-t=b)a!a_z9')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    # "jazzmin",  # Temporarily disabled - not installed
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "rest_framework",
    "rest_framework_simplejwt",
    'corsheaders',
    'pos.apps.PosConfig',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME_DAYS', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME_DAYS', '90'))),
    'ROTATE_REFRESH_TOKENS': os.getenv('JWT_ROTATE_REFRESH_TOKENS', 'False').lower() == 'true',
    'BLACKLIST_AFTER_ROTATION': os.getenv('JWT_BLACKLIST_AFTER_ROTATION', 'False').lower() == 'true',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True').lower() == 'true'
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if origin.strip()
]


ROOT_URLCONF = 'posbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'posbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Database Configuration with Environment Support
DATABASE_URL = os.getenv('DATABASE_URL', f'sqlite:///{os.path.join(USER_DATA_PATH, "db.sqlite3")}')

DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "POS Admin",
    "site_header": "POS Admin",
    "site_brand": "VARANDA POS",
    "copyright": "VPOS",
    "show_sidebar": True,
    "navigation_expanded": True,

    "default_icon_parents": "fa fa-folder",
    "default_icon_children": "fa fa-circle",

    "icons": {
        # 📦 Produk & Inventoriu
        "pos.Product": "fas fa-box",
        "pos.Category": "fas fa-tags",
        "pos.Unit": "fas fa-balance-scale",
        "pos.Supplier": "fas fa-truck",
        "pos.StockAdjustment": "fas fa-tools",

        # ❗ FA5
        "pos.StockMovement": "fas fa-exchange-alt",
        "pos.Stock": "fas fa-cubes",
        "pos.Warehouse": "fas fa-warehouse",

        # 💵 Transaksi & Purchase
        "pos.Transaction": "fas fa-receipt",
        "pos.ProductReturn": "fas fa-undo",
        "pos.Purchase": "fas fa-shopping-cart",
        "pos.PurchaseReturn": "fas fa-clipboard",
        "pos.PurchaseItem": "fas fa-cart-plus",
        "pos.Bank": "fas fa-university",
        "pos.BankPayment": "fas fa-money-check-alt",

        # 🔁 Stock Transfers
        "pos.StockTransfer": "fas fa-exchange-alt",

        # 👥 Pelanggan
        "pos.Customer": "fas fa-user",
        "pos.Profile": "fas fa-id-badge",

        # 🏬 Toko
        "pos.StoreProfile": "fas fa-store",

        # ⭐️ Poin (NEW)
        "pos.PointsEarningRule": "fas fa-coins",
        "pos.PointsRedemptionRule": "fas fa-gift",
        "pos.PointsLedger": "fas fa-history",

        # 🔒 Administrasaun
        "auth.User": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
        "pos.BackupUpload": "fas fa-upload",
    },

    # Grup menu di sidebar
    "models": {
        # Grup Transaksi
        "pos.Transaction": "Transaksi",
        "pos.ProductReturn": "Transaksi",
        "pos.Purchase": "Transaksi",
        "pos.PurchaseItem": "Transaksi",
        "pos.PurchaseReturn": "Transaksi",
        "pos.StockTransfer": "Transaksi",
        "pos.Bank": "Transaksi",
        "pos.BankPayment": "Transaksi",

        # Grup Produk
        "pos.Product": "Produk",
        "pos.Category": "Produk",
        "pos.Unit": "Produk",
        "pos.Supplier": "Produk",
        "pos.StockAdjustment": "Produk",

        # Grup Pelanggan
        "pos.Customer": "Pelanggan",
        "pos.Profile": "Pelanggan",

        # Grup Toko
        "pos.StoreProfile": "Toko",

        # Grup Poin (NEW)
        "pos.PointsEarningRule": "Poin",
        "pos.PointsRedemptionRule": "Poin",
        "pos.PointsLedger": "Poin",

        # Admin
        "auth.User": "Administrasaun",
        "auth.Group": "Administrasaun",
        "pos.BackupUpload": "Administrasaun",
    },

    "order_with_respect_to": [
        "pos.Category",
        "pos.Unit",
        "pos.Product",
        "pos.StockAdjustment",
        "pos.Supplier",
        "pos.Transaction",
        "pos.ProductReturn",
        "pos.Purchase",
        "pos.PurchaseItem",
        "pos.PurchaseReturn",
        "pos.StockTransfer",

        # Pelanggan
        "pos.Customer",
        "pos.Profile",

        # Poin (NEW) — urutkan dekat Pelanggan jika mau
        "pos.PointsEarningRule",
        "pos.PointsRedemptionRule",
        "pos.PointsLedger",

        # Toko & Admin
        "pos.StoreProfile",
        "auth.User",
        "auth.Group",
        "pos.BackupUpload",
    ],

    "custom_links": {
        "pos.Transaction": [
            {
                "name": "📦 Backup Data",
                "url": "backup_data",
                "icon": "fa fa-download",
                "permissions": ["auth.view_user"]
            }
        ]
    },
}

